Fix for numpy 2.5 removal of deprecated support of round(complex)
Using the numpy complex types with the built-in Python round function
was deprecated in numpy 1.9, and removed in numpy 2.5, causing:

TypeError: type numpy.complex128 doesn't define __round__ method

Follow the suggested alternative of using numpy.round function instead.